### ISSUE TITLE
Frontend build out

### ISSUE THREAD

**Issue by thedrewery** [thedrewery/hot-chicken#13]
@jasonbarry hot-chicken (aka Koo Koo Drew) is all set to deploy as an API. So, I'm ready to start building out the frontend in React. Wanted your input on whether it makes the most sense to use Netlify to deploy and start a new repo referencing hot-chicken endpoints, or if it's better to continue to build out the frontend within the same repo.

**Comment by jasonbarry** [comment]
@thedrewery where do you plan on hosting the backend? You can host the whole thing on Netlify, but you'd have to make the backend compatible in a serverless environment

**Comment by thedrewery** [comment]
@jasonbarry got it, that answers my question. I love serverless, but that's for another project. I'll host the backend on Render and create a new repo for the frontend hosted by Netlify. Thanks!
